therocktitan/apps/superuser/urls.py
from django.urls import path
from . import views

app_name = 'app_superuser'
urlpatterns = [
    path('', views.login, name="login"),
    path('home/', views.home, name="home"),
    path('validation/', views.validation, name="validation"),
    path('blog/', views.blog, name="blog"),
    path('malphite_guide/', views.malphite_guide, name="malphite_guide"),
    path('logout/', views.logout, name="logout"),
]

therocktitan/therocktitan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/', 
         admin.site.urls),
    path('', 
        include('apps.client.urls')),
    path('superuser-rocktitan/', 
        include('apps.superuser.urls')),
]

therocktitan/apps/superuser/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return "{0}".format(self.username)

therocktitan/apps/superuser/forms.py
from django import forms
from .models import User

class UserLogin(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length = 50, widget=forms.PasswordInput)

    class Meta:
        # model
        model = User

        # displaying fields
        fields = '__all__'

    # method for cleaning the data
    def clean(self):
        super(UserLogin, self).clean()

        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        
        return self.cleaned_data

therocktitan/apps/superuser/views.py
from django.shortcuts import render
from .models import User
from .forms import *
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


# Create your views here.


def login(request):
    return render(request, 'superuser/login.html')


def home(request):
    return render(request, 'superuser/home.html')


def blog(request):
    return render(request, 'superuser/blog.html')

def malphite_guide(request):
    return render(request, 'superuser/malphite_guide.html')

def logout(request):
    return


def validation(request):
    if request.method == "POST":
        form = UserLogin(request.POST)
    if form.is_valid():
        try:
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = User.objects.get(username=username, password=password)
            return HttpResponseRedirect(reverse_lazy('app_superuser:home'))
        except:
            messages.error(request, 'Usuario o Contraseña Incorrecta')
    else:
        form = UserLogin()
        messages.error(request, 'Usuario o Contraseña Incorrecto')
    return render(request, 'superuser/login.html', {'form': form})

therocktitan/templates/superuser/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property=”og:locale” content=”en_US”>
    <meta property=”og:type” content=”website”>
    <link rel="icon" href="{% static 'img/rocktitan_logo.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block link %} {% endblock %}
    <script src="https://kit.fontawesome.com/f04d0469dd.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <i><img src="{% static 'img/rocktitan_logo.png' %}" style="height: 30px; width: 30px;"></i>
      </a>
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_superuser:blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_superuser:malphite_guide' %}">Malphite Guide</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app_superuser:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<body>
{% block body %}
{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

therocktitan/templates/superuser/home.html
{% extends "superuser/base.html" %}
{% load static %}
{% block title %}Master Login{% endblock %}
{% block body %}


{% endblock %}

therocktitan/templates/superuser/login.html
{% extends "superuser/base.html" %}
{% load static %}
{% block title %}Master Login{% endblock %}
{% block body %}
{% if messages %}
{% for message in messages %}

<div class="alert alert-success" role="alert">
    <button type="button" class="btn-close" aria-label="Close"></button>
    <strong class="text-dark">{{ message }}</strong>
</div>
{% endfor %}
{% endif %}
<form action="{% url 'app_superuser:validation' %}" method="POST"> 
    {% csrf_token %}
    <section class="vh-100" style="background-color: #262323;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card shadow-2-strong" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">
      
                  <h3 class="mb-5">Sign in</h3>
      
                  <div class="form-outline mb-4">
                    <label class="form-label" for="typeEmailX-2">Username</label>
                    <input type="username" name="username" class="form-control form-control-lg" />
                  </div>
      
                  <div class="form-outline mb-4">
                    <label class="form-label" for="typePasswordX-2">Password</label>
                    <input type="password" name="password" class="form-control form-control-lg" />
                  </div>
      
                  <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</form>
  {% endblock %}