therocktitan/apps/client/urls.py
from django.urls import path
from . import views

app_name = 'client'
urlpatterns = [
    path('', views.home, name="home"),
    path('category/', views.category, name="category"),
    path('macro_and_micro/', views.macro_and_micro, name="macro_and_micro"),
    path('matchup/', views.matchup, name="matchup"),
    path('runes/', views.runes, name="runes"),
    path('items_and_builds/', views.items_and_builds, name="items_and_builds"),
    path('update_logs/', views.update_logs, name="update_logs"),
    path('blog/', views.blog, name="blog"),
    path('policy/', views.policy, name="policy"),
]

therocktitan/therocktitan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        'admin/', 
         admin.site.urls),
    path('', 
        include('apps.client.urls')),
    path('superuser-rocktitan/', 
        include('apps.superuser.urls')),
]

therocktitan/apps/client/models.py
from django.db import models


# Create your models here.

class Champion(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}".format(self.id, self.name)


class Path(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(default="description")
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}".format(self.id, self.name)


class Keystone(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}".format(self.id, self.name)


class Alternative_Keystone(models.Model):
    alternative_keystone =  models.ForeignKey(Keystone, null=True, blank=True, on_delete=models.CASCADE)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{0}".format(self.alternative_keystone)



class Slot_Rune_One(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}({0})".format(self.id, self.name)


class Slot_Rune_Two(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}({0})".format(self.id, self.name)


class Slot_Rune_Three(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}({0})".format(self.id, self.name)


class Slot_Shard_One(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}({0})".format(self.id, self.name)


class Slot_Shard_Two(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}({0})".format(self.id, self.name)


class Slot_Shard_Three(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    
    #Show data when we wanna print an object
    
    
    def __str__(self):
        return "{1}({0})".format(self.id, self.name)

class Item(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=60)
    
    
    def __str__(self):
        return "{0}".format(self.name)


class Skill_Max(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=10)
    
    
    def __str__(self):
        return "{0}".format(self.name)


class Difficulty(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=20)
    
    
    def __str__(self):
        return "{0}".format(self.name)


class Rune(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    path = models.ForeignKey(Path, null=False, blank=False, on_delete=models.CASCADE)
    keystone = models.ForeignKey(Keystone, null=False, blank=False, on_delete=models.CASCADE)
    slot_rune_one = models.ForeignKey(Slot_Rune_One, null=False, blank=False, on_delete=models.CASCADE)
    slot_rune_two = models.ForeignKey(Slot_Rune_Two, null=False, blank=False, on_delete=models.CASCADE)
    slot_rune_three = models.ForeignKey(Slot_Rune_Three, null=False, blank=False, on_delete=models.CASCADE)
    slot_shard_one = models.ForeignKey(Slot_Shard_One, null=False, blank=False, on_delete=models.CASCADE)
    slot_shard_two = models.ForeignKey(Slot_Shard_Two, null=False, blank=False, on_delete=models.CASCADE)
    slot_shard_three = models.ForeignKey(Slot_Shard_Three, null=False, blank=False, on_delete=models.CASCADE)
    notes = models.TextField(null=False, blank=True)


class Matchup(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    champions = models.ForeignKey(Champion, null=False, blank=False, on_delete=models.CASCADE)
    rune = models.ForeignKey(Keystone, null=True, blank=True, on_delete=models.CASCADE)
    slot_rune_one = models.ForeignKey(Slot_Rune_One, null=True, blank=True, on_delete=models.CASCADE)
    slot_rune_two = models.ForeignKey(Slot_Rune_Two, null=True, blank=True, on_delete=models.CASCADE)
    slot_rune_three = models.ForeignKey(Slot_Rune_Three, null=True, blank=True, on_delete=models.CASCADE)
    alternative_keystone =  models.ForeignKey(Alternative_Keystone, null=True, blank=True, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, null=False, blank=False, on_delete=models.CASCADE)
    skill_max = models.ForeignKey(Skill_Max, null=False, blank=False, on_delete=models.CASCADE)
    difficulty = models.ForeignKey(Difficulty, null=False, blank=False, on_delete=models.CASCADE)
    comments =  models.TextField()
    notes = models.TextField(null=False, blank=True)


    def __str__(self):
        return "{0}{1}".format(self.champions, self.id)


class Update(models.Model):
    id = models.PositiveSmallIntegerField(primary_key=True)
    date = models.DateField()
    comments =  models.CharField(max_length=1000)


    def __str__(self):
        return "{0}".format(self.date)

therocktitan/apps/client/views.py
from django.shortcuts import render
from .models import *


# Create your views here.


def home(request):
    return render(request,"client/home.html")


def category(request):
    return render(request,"client/category.html")


def macro_and_micro(request):
    return render(request,"client/macro_and_micro.html")


def policy(request):
    return render(request,"client/policy.html")


def matchup(request):
    matchup = Matchup.objects.all()
    return render(request,"client/matchup.html", {"matchup":matchup})


def runes(request):
    return render(request,"client/runes.html")


def items_and_builds(request):
    return render(request,"client/items_and_builds.html")


def update_logs(request):
    update_logs = Update.objects.all()
    return render(request,"client/update_logs.html", {"update_logs":update_logs})


def blog(request):
    return render(request,"client/blog.html")

therocktitan/templates/client/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property=”og:locale” content=”en_US”>
    <meta property=”og:type” content=”website”>
    <link rel="icon" href="{% static 'img/rocktitan_logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/header.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/scroll.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" type="text/css">
    {% block link %} {% endblock %}
    <script src="https://kit.fontawesome.com/f04d0469dd.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <section>
        <input type="checkbox" id="check">
        <header>
          </div>
          <h2><a href="#" class="logo"></a></h2>
          <div class="navigation">
              <a href="{% url 'client:home' %}">Home</a>
              <a href="{% url 'client:items_and_builds' %}">Items and Builds</a>
              <a href="{% url 'client:macro_and_micro' %}">Macro and Micro</a>
              <a href="{% url 'client:matchup' %}">Matchups</a>
              <a href="{% url 'client:runes' %}">Runes</a>
              <a href="{% url 'client:blog' %}">Blog</a>
              <a href="{% url 'client:update_logs' %}">Updates</a>
          </div>
          <label for="check">
          <i class="fas fa-bars menu-btn"></i>
          <i class="fas fa-times close-btn"></i>
          </label>
        </header>
        {% block section %}{% endblock %}
    </section>
    {% block content %}{% endblock %}
    <footer>
        The Rock Titan Guide was created under Riot Games' "Legal Jibber Jabber" policy using assets owned by Riot Games.
        Riot Games does not endorse or sponsor this project. <br>
        This is ONLY a fan project created with <i class="fas fa-heart" style="color: #f85656;"></i>. No profit, No commercial. <a href="/policy" style="color: #deeb71; text-decoration: none; font: bolder;"> More information here </a>
    </footer>
</body>
</html>

therocktitan/templates/client/blog.html
{% extends "client/base.html" %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" type="text/css">
{% endblock %}
{% block title %}Blog{% endblock %}
{% block section %}
<div class="container-title">
    <div class="title">
        <h2>Comming Soon...</h2>    
    </div>
</div>
{% endblock %}

therocktitan/templates/client/category.html
{% extends "client/base.html" %}
{% load static %}
{% block link %}
    <link href="{% static 'css/category.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block title %}Category{% endblock %}
{% block section %}
        <div class="cards-wrapper">
            <div class="card-grid-space">
              <a class="card" href="{% url 'client:macro_and_micro' %}" style="--bg-img: url('{% static 'img/category/macro_and_micro.png' %}')">
                <div>
                  <h1 style="color: rgb(255, 91, 91);">Macro and Micro</h1>
                  <p>
                    Everyone is going to tell you up front,
                    don't worry, you're a tank. But you need to do a lot more than that to get to climb!
                  </p>
                  <div class="tags">
                    <div class="tag" style="background-color: rgb(255, 91, 91); color: rgb(255, 255, 255);">Mac&Mic</div>
                  </div>
                </div>
              </a>
            </div>
            <div class="card-grid-space">
              <a class="card" href="{% url 'client:matchup' %}" style="--bg-img: url('{% static 'img/category/matchups.png' %}')">
                <div>
                  <h1 style="color: #effd6f;">Match ups</h1>
                  <p>You must learn about it to climb!</p>
                  <div class="tags">
                    <div class="tag" style="background-color: rgb(239, 253, 111); color: rgb(12, 11, 11);">Matchups</div>
                  </div>
                </div>
              </a>
            </div>
            <div class="card-grid-space">
              <a class="card" href="{% url 'client:runes' %}" style="--bg-img: url('{% static 'img/category/runes.png' %}')">
                <div>
                  <h1 style="color: rgb(91, 116, 255);">Runes</h1>
                  <p>Take in consideration about it, not always you're using the same runes</p>
                  <div class="tags">
                    <div class="tag" style="background-color: rgb(91, 116, 255); color: rgb(12, 11, 11);">Runes</div>
                  </div>
                </div>
              </a>
            </div>
            <div class="card-grid-space">
                <a class="card" href="{% url 'client:items_and_builds' %}" style="--bg-img: url('{% static 'img/category/items_and_builds.png' %}')">
                  <div>
                    <h1 style="color: rgb(255, 91, 200);">Items and Builds</h1>
                    <p>Starting, middle and late items.</p>
                    <div class="tags">
                      <div class="tag" style="background-color: rgb(255, 91, 200); color: rgb(12, 11, 11);">Items&Builds</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="card-grid-space">
                <a class="card" href="{% url 'client:update_logs' %}" style="--bg-img: url('{% static 'img/category/updatelog.png' %}')">
                  <div>
                    <h1 style="color: rgb(250, 162, 224); ">Update Log</h1>
                    <p>Check the last updates that I've been doing to the page don't die</p>
                    <div class="tags">
                      <div class="tag" style="background-color: rgb(250, 162, 224); color: rgb(12, 11, 11);">Updates</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="card-grid-space">
                <a class="card" href="{% url 'client:blog' %}" style="--bg-img: url('{% static 'img/category/blogs.png' %}')">
                  <div>
                    <h1 style="color: rgb(250, 212, 162); ">Blogs</h1>
                    <p>Check it out my personal blog!</p>
                    <div class="tags">
                      <div class="tag" style="background-color: rgb(250, 212, 162); color: rgb(12, 11, 11);">Blog</div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
    </section>
{% endblock %}

therocktitan/templates/client/home.html
{% extends "client/base.html" %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
{% endblock %}
{% block title %}Home{% endblock %}
{% block section %}
<div class="content">
    <div class="info">
      <h2>Welcome! <br><span>I'm The Rock Titan!</span></h2>
      <p>
        This guide is intended to anyone that wants to learn Malphite at a <font style="color: #f85656;">High level</font>.
        This guide alone does not guarantee that you will get a high rank but will significantly raise your chances.
        Other guides about top laning and general game knowledge <font style="color: rgb(89, 255, 145);">will help you climb as well</font>.
      </p>
      <a href="/category" class="info-btn">Start</a>
    </div>
</div>
<div class="media-icons">

    <a href="http://discord.gg/RW84RkqZBD"><i class="fab fa-discord"></i></a>
    <a href="https://twitter.com/therocktitanlol"><i class="fab fa-twitter"></i></a>
    <a href="https://www.twitch.tv/therocktitan"><i class="fab fa-twitch"></i></a>
</div>
{% endblock %}

{% block content %}
<section>
    <div class="content-about">
        <div class="info">
            <h2>About me</h2>
            <p>
                I am a <font style="color: #f85656;">Malphite OTP</font> and I hit Master playing only <font style="color: #758eff;">Malphite!</font><br>
                For anyone that wants to climb but <font style="color: rgb(250, 114, 198);">don't have the mechanics to do</font> so, <font style="color: #758eff;">Malphite</font> is your champ!<br>
                Once in a while I get called, <font style="color: #f0ff6b;">"braindead Malphite player"</font> or <font style="color: #f0ff6b;">"Must be boring being a Malphite one trick"</font> but when you win and climb, you don't care what they say anymore!
                <font style="color: #758eff;">Malphite</font> mains are humble, they know they are bad at video games so instead of trying to see who clicks the fastest, they admit defeat and play <font style="color: #758eff;">Malphite!</font>
                <br>This is me... a 24 year old boomer that can't compete with the 16 year old gaming prodigy at this game.
            </p>
        </div>
        <div class="image-rock">
            <img src="{% static 'img/therock_teacher.png' %}">
        </div>
    </div>
</section>
{% endblock %}

therocktitan/templates/client/macro_and_micro.html
{% extends "client/base.html" %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/macro_and_micro.css' %}" type="text/css">
{% endblock %}
{% block title %}Macro and Micro{% endblock %}
{% block section %}

<div class="container-title">
    <div class="title">
        <h2>Macro and Micro</h2>    
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>How to become a good Malphite player?</h3>
    </div>
    <div class="info">
        <p>
            Lets get a few obvious things out of the way.<br>
            Everyone is going to tell you up front, don't worry, you're a tank, you'll be good in later on in teamfights.
            That is true but you need to do a lot more than that to get to climb!
        </p>
    </div>
</div>

<div class="container-title">
    <div class="title">
        <h2>Macro</h2>    
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>1. You need to know your match ups. Know what to do vs the common match ups. </h3>
    </div>
    <div class="info">
        <p>
            Things like Camille, Darius, Shen, Aatrox, Irelia, and Fiora you must know what to do against these Champs!
        </p>
    </div>
</div>
<div class="container">
    <div class="title">
        <h3>1.1 Laning and Trading </h3>
    </div>
    <div class="info">
        <p>
        Many people think lane phase for Malphite is not important because Malphite excels in teamfights. However, this is not true for high elo.
        <br> Getting to Diamond relies heavily on properly handling your match up. There are about 50 of them and lucky for you, I made a match up guide for you :)
        <br> Getting to Master means you need to stomp or hard win your winning match ups. Exploit opponent's mistakes if you're against unfavored match ups.
        <br> Then doing all that while not dying to jungle ganks and looking for TP plays.
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>1.2 Against Tank Match ups </h3>
    </div>
    <div class="info">
        <p>
            I always find it unrewarding winning lane against, Sion, Cho'Gath, Ornn and even Maokai...
            <br>First of all, you lose in all these match ups, any good Sion and Cho'Gath will win this lane easily.
            Now lets say you do win against them, they made a big mistake and you get a kill on them...
            <br>The problem is, if their team is better, you're going to lose anyway because Sion and Cho'Gath is never going to be completely useless...
            They are also playing hoping their team is going to carry them just like you...
            <br>So I find the best way to win the game (not your lane), is to have more Kill Participating than them.
            If you helped your team thrive more than him, you'll most likely win the game.
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>2. By knowing your match ups, you'll need to know your lane Prios </h3>
    </div>
    <div class="info">
        <p>
            Things like telling your jungler to start top side or push your lane to gain lane prio.
            Do you win top/jg 2v2s? If not, tell your jungler to never gank top!
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>3. Wave control. </h3>
    </div>
    <div class="info">
        <p>
            Know how to freeze and break freezes!
            This is extremely important, I really recommand watching a video on this!
        </p>
    </div>
</div>


<div class="container">
    <div class="title">
        <h3>4. How to farm. </h3>
    </div>
    <div class="info">
        <p>
            A lot of the time you are going to get bullied.
            <br>Is it worth it to trade half your HP bar for 1 range minion? NO!
            <br>Only get the CS that's worth getting! Don't take too much damage trying to get 14 gold!
            <br>Sometimes, if you think you might die for a Cannon minion, you're just going to have to let it die in front of you. Don't. Be. Greedy.
        </p>
    </div>
</div>


<div class="container">
    <div class="title">
        <h3>5. Know what to build (Itemization) </h3>
    </div>
    <div class="info">
        <p>
            Every game your build can be different. In my items/builds guide, I mentioned how it is very difficult to have one build fits all, or best in slot.
            <br>But in general, you should think about itemization during champ select and loading screen.
            <br>Since the Hullbreaker buff, split pushing is becoming a real issue. You'll need to match your split pusher a lot of the times.
            <br>You should strictly itemize against the split pusher. What's the point of buying MR for teamfighting when you're trying to stop a trynd for most of the game
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>6. Know when to ult.</h3>
    </div>
    <div class="info">
        <p>
            Your ult is a big decision, if you're the only engage on your team, the outcome of a teamfight will depend on whether your ult is good or not.
            Don't engage when none of your teammates are around. You might see a 5 man ult opportinuty but if teammate is around, control urges!
            If you can't find a 5 man ult, don't be greedy! Just ult the best available target!*
            Ideally you want your ult to always be on CD. Use it to roam all the time!
            Don't forget to use your ult as an escape! If enemy jungler ganks top and you ult away? You've wasted his time! Hopefully your team can get Drake off that.
            I find landing your ult more and more difficult now... So many dashes and jumps. It's so nuts...
            So you don't always need to engage with your ult, you can use it to zone mid fight and ult when the enemy exposes weakness because they need to extend to do damage
            * In high elo especially, people just know how to play against your ult, it'll be rare to find two carries stacked up on top of each other.
            This is why I love comps that has one hyper carry, then I can single out who to ult. You should already be thinking about who to ult when you're on the loading screen
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>7. How to use Granite shield?</h3>
    </div>
    <div class="info">
        <p>
            Get your W and E off before your Granite shield is gone!
            Farm around your Granite shield! You don't want to get too low in lane!
        </p>
    </div>
</div>


<div class="container-title">
    <div class="title">
        <h2>Micro</h2>    
    </div>
</div>


<div class="container">
    <div class="title">
        <h3>1. Get your TEAM fed!</h3>
    </div>
    <div class="info">
        <p>
            If you are winning topside, transfer your lead to the rest of the team (also known as... Carrying)!
            <br>Carrying means you've contributed the most toward winning the game. If you're ahead, you must carry as a tank, one way or another!
            <br>Give your kills to your jungler, give your kills to your adc. You don't need it!
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>1.5 Map awareness is very important! It gets your team fed!</h3>
    </div>
    <div class="info">
        <p>
            Since you only play one champ so you know this champ inside out, look at the mini map more!
            <br>Your post 6 roams, hovers and TP plays are very strong and if used well, you can win games just with Map awareness alone!
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>2. Roaming and TP ganks</h3>
    </div>
    <div class="info">
        <p>
            This topic is in my opinion, very advanced. I'm not even an expert at this, if you are, you should be a coach.
            <br>Roaming and TP comes with a lot of experience, if you were once a jungler, you have a better edge at this.
            <br>You need to be able to look at a lane state and/or a small skirmish and determine whether moving there or TPing is going to do anything.
            <br>In general, you should be greedy with your TPs, use your TP if your team can get at least one kill + burn the other guy's summoners or get an objective right after.
            <br>Many times, it's just better to use TP for yourself, back to your lane because you're playing a bad match up most of the time (or to your prio).
            <br>This is why if you use your TP and got nothing out of it, you just fucked yourself even more. Be very greedy with your TP ganks, make sure you get a lot out of your TP
            <br>As for Roaming, you don't have much of a choice other than Mid. If they have Vlad mid, Ahri mid, you're out of luck...
            <br>If there is a fight happening in river but you are pushed into your turret, do you farm your wave or move to the fight?
            <br>You need to give up the farm and move to the fight or else your team loses the fight. You rather lose the wave than lose the fight!
            <br>Similar story with TP, if you're farming a wave at turret then a fight happens bot, give up the wave and TP bot immediately.
            <br>If you have lane prio and you can't gank mid, best thing to do is to get vision control in enemy team's jungle (or get free recall off if you have time)
            <br>Malphite doesn't need CS to succeed, always give up your waves to win fights! You'll have your R button whether you are farmed or not!
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>3. Split Pushing</h3>
    </div>
    <div class="info">
        <p>
            Split push generally when you have your TP up.
            Grouping and Teamfighting is a coinflip, everyone is sharing gold and exp from one lane. Side waves are all going to waste.
            However, you must realize that it is very hard for Malphite to split push because you have no escape!
            If you can't split push, wave clear the side wave and look for fights!
            Get infinite pinks and sweepers and get your team to help clear enemy vision so you can get a fight off
            Here are some invisible lines on the map that you can't cross unless the nearby jungle is warded
        </p>
        <br>
        <div class="img-container">
            <img src="{% static 'img/lol_map_split_push.png' %}" alt="" style="height: 300px; width: 300px;">
        </div>  
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>3.5 Matching the Split Pusher</h3>
    </div>
    <div class="info">
        <p>
            Against any type of split pusher, your goal is to not fall behind or try to win against them in the early game, lane phase
            In the early game, try to get the jungler to gank and finish the gank as quickly as possible so he can go back helping the rest of the team
            That means set up your wave so when your jungler comes, it's an in and out gank!
            Buy items to counter them, as mentioned in #5 in Micro
            Always try to clear the wave as much as possible before they reach your turret
        </p>
    </div>
</div>

<div class="container">
    <div class="title">
        <h3>4. Teamfighting</h3>
    </div>
    <div class="info">
        <p>
            It's almost too hard to put this in writing, many factors can affect the out come of a teamfight.
            <br>Factors such as: itemization, vision control, item advantage, team comps are things you need to consider before hand when teamfighting
            <br>A major factor for teamfighting with Malphite is your Ult useage, please refer back to #6 in Micro
            <br>The most common form of teamfighting is a "Front to Back" style teamfight.
            <br>However, Malphite is general not a great front to back teamfighter because you offer no peel and kiting abilities for your team
            <br>Sometimes you may be forced to use your ult defensively so your Jinx can live
            <br>If you need to play for backline carries, try to go everfrost. This is great against enemy team with dive comps
            <br>The best scenario for a Malphite teamfight is an early pick on a priority target
            <br>Or you are able to find a blind spot in enemy vision and get a surprise ult off
        </p>
    </div>
</div>


<div class="container">
    <div class="title">
        <h3>5. Vision control</h3>
    </div>
    <div class="info">
        <p>
            Ward more! It literally saves your life!
            <br>If your lane is pushed up to the enemy's turret, don't just walk back to lane... ward first. Chances are there is a jungler waiting for you to get back to lane...
            <br>If your lane is pushed, you're also warding your top laner to track his movement.
            <br>Pinks are so important, guys literally watch your replays, sometimes you feel so stupid standing in a bush that is warded the whole time lol...
            <br>You need pinks to pull off engages and surprise ults!
        </p>
    </div>
</div>


<div class="container">
    <div class="title">
        <h3>Any game knowledge is going to increase your chances of achieving a higher rank!</h3> <br>
        <h3>To make up for your lack of skill, you must have very deep game knowledge!</h3> <br>
        <h3>Good Luck!</h3>
    </div>
</div>


{% endblock %}

therocktitan/templates/client/update_logs.html
{% extends "client/base.html" %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'css/update_logs.css' %}" type="text/css">
{% endblock %}
{% block title %}Update Logs{% endblock %}
{% block section %}
<div class="timeline-area">
    <div class="container">
        <div class="timelines">
            <h2><font style="color: #f0ff6b;">Updates</font></h2>
        </div>
        <div class="all-timelines">
        <!--SINGLE TIMELINE-->
        {% for i in update_logs %}
            <div class="single-timeline d-flex-2">
                <div class="timeline-blank"></div>
            <div class="timeline-text d-flex-2">
            <span>
                <h6><font style="color: #f85656;">{{i.date}}</font></h6> — {{i.comments}}
            </span>
            <div class="t-square"></div>
            </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}